const fs = require('fs');

// Keys provided by user
const FIREBASE_PROJECT_ID = "prepwise-d70c8";
const FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@prepwise-d70c8.iam.gserviceaccount.com";
const FIREBASE_PRIVATE_KEY = `-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxUt1fM2vIm9GX\nSsqDsoebEy/Og7F9Oplx/C/reBxwUHK/Qcx9OTXuRHH2P1VazPUnG3f4L+2orYuL\nhjzJv4AbXa/z4CuSVfM0w7xPefA8a+Qdb/mZEtKfDQ70QZQstjbi439z+Bxtz+UC\nm+pS/mzJ8a9pgybp+F1DRwP5O/Jz0eVskC4gJ9btRdmNHMj3hMhPylrj0p9H+Jj9\nE81d7YoQ5MwZU47CSBGgZ5BS3X9cI73vE7jgIJblhU5kX2BsSfpd9bjfbDv0W8Cf\nnB+nqX651/brXXOeblxXKR3VETBQZ1aiQ/12pi2P8vb52dQERcsScXveHaXCNHa4\nI7EPvs2tAgMBAAECggEAHGmfqPJvUcyNz8UfH+0KR3HSli+Jz/wEvDvhXcR4IhLx\n3+1mG6aAGraC4CcTwSHYIjUHiw/6760nD+spcFYr67aeS+Beeusktg6q7L0oHjZX\nbdQUVU+ryepovACKAoQL1V0IfgeCXqISGtHqwPOdcNo19h0ariCqqO4HF/dgCOiT\noigRH8+J1WFCs3NTqg0h9Lew+mj9glIYnjZW0U1aezpymNhRNn3jrVazPKXxl9WM\nvfYAT/80WfmQBE0Ga0WRmWX78Av/33GRHSAeVdZWBsO7Vn8FuMMZN6JbihIwWgE8\nKWsBhdHXO+dX1BhTyL5K5ejBsIP5jryQJ1AfE3r/jQKBgQDaoxuQKzd+k4S2yCst\ntALrJahxylshJ13Kmhw4+wB8UzHPP6bdEoPqQyCaXSwlGqCMIkgyYyXwmDg2TJ6C\nr2mg4XLF2O9jyfZzpQP/SH5wr+MMF6+1O6bJO+z2+C75rlWLh/RcF8UPmXxTVCpX\nmccMwETe+Ah3cy//64hjSmwvDwKBgQDPoGKFb1PqhuCCVzDEy7D2mFtaoNeSIneU\noEfI26URoJ4Af/zZgGVj0VvpkSBkLvT0nx2gO2mQW1hn76ZGob5FeOnkX37eqfVX\nJvtozT7nAZnJl95+4oDtBXNp93zDfPNwGxZLExPMhRz08HNxwsSri2Y6uCldV5JG\n+K0wL1G3gwKBgQCMsjYEmqsFm2zmKv4OVS8jn4I8Z9opBapHvNC4ol33o5oEIpQA\n4+9cC4Kpk5fa8L2sMEuBkWhS4cIav0eqFbPFwg8X3rh+4PLmDKT73OzxG17i40NB\nP3ffO98MNz4Tkuqd9gl8UheQKFdnUFxHL0B2piwryDW6mLek2y9TpgrkZQKBgDpz\neoj6KHOz+Ox4w2ADwBQMHFvNQCMB1QxgexUO0M+/mfumDHbm8KRDQk7k7muF1Kwx\nR1Pepf9f1+mazALCciB4w8/Gnxw+ILKlKiSb4z1JGheeuLZvVX83NsOM2+Nc7Mx\nzPrhqgc/ykEimD2EiX2JxwPs6KhAiQu14nvYNnclAoGAbrGfhFSuRf9CiTiAABlt\nwlaNIcnt7/JrVIEey+qKwMn+BSRQNpADK54SMqRpMFt/pG/Yt9QeZHP5cTzX8d7Z\nWjBLT5YiCmopugcYkKvk7C+08ZJK5MvN8mYsVDFezyaD+2f2nyMzr10Kljl6AUYu\ncP+oBhnRikKQAtK3LEOrQ4o=\n-----END PRIVATE KEY-----`;

const NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyDU_SSSPwI1XGHhJsyXZOgqC6b70NDvjkE";
const NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "prepwise-d70c8.firebaseapp.com";
const NEXT_PUBLIC_FIREBASE_PROJECT_ID = "prepwise-d70c8";
const NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "prepwise-d70c8.firebasestorage.app";
const NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "517268626852";
const NEXT_PUBLIC_FIREBASE_APP_ID = "1:517268626852:web:66d223a85255dc8c34b531";

const GOOGLE_GENERATIVE_AI_API_KEY = "AIzaSyD8gIiTzNeYgChUDJ6rOM1UV438DrIGr4o";
const NEXT_PUBLIC_BASE_URL = "http://localhost:3000";

const envContent = `
# Firebase Backend
FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
FIREBASE_PRIVATE_KEY="${FIREBASE_PRIVATE_KEY.replace(/\n/g, '\\n')}"

# Firebase Frontend
NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}

# Google AI
GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}

# App
NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
`.trim();

fs.writeFileSync('.env.local', envContent);
console.log(".env.local has been reconstructed successfully.");
